logging:
    level:
        eureka:
            client:
                healthcheck:
                    enabled: true
                service-url:
                    defaultZone: http://user:admin@localhost:8761/eureka/
            instance:
                prefer-ip-address: true
        management:
            endpoint:
                health:
                    show-details: when_authorized
            endpoints:
                web:
                    base-path: /application
                    exposure:
                        include: '*'
            security:
                enabled: false
        org:
            org:
                hibernate: info
            springframework: info
server:
    port: 8001
spring:
    application:
        name: microservice-provider-user
    datasource:
        data: classpath:data.sql
        platform: h2
        schema: classpath:schema.sql
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                web-allow-others: true
    jpa:
        generate-ddl: false
        hibernate:
            ddl_auto: none
        show-sql: true
