server:
    port: 8011
profile: movie-dev-v2.0    
user:
    userServiceUrl: http://localhost:8001/
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    service-url:
      defaultZone: http://user:admin@localhost:8761/eureka/