server:
    port: 8010
profile: movie-prod-v1.0
user:
    userServiceUrl: http://localhost:8000/
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    service-url:
      defaultZone: http://user:admin@localhost:8761/eureka/
  instance:
    prefer-ip-address: true      