server:
    port: 8011
profile: movie-dev-v2.0    
user:
    userServiceUrl: http://localhost:8001/
spring:
  application:
    name: microservice-consumer-movie
logging:                           #配置日志级别，让Hibernate 打印执行的SQL
  level:
    org.springframework: info
    org.hibernate: info    
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:admin@localhost:8761/eureka/
  instance:
    prefer-ip-address: true      