server:
  port: 8001
profile: '{cipher}AQAaSQVdF1nyrN+B81xo5JvzulhgGtRpZPeRtY9izaOGgUleAmz/nQHeDdEBQw4g4/Psp+fFqxloDtK0e0XXL7OOZmg3jvp1YKQjl+L5zzuOJZ2BT6XKDLYOoeqSx2Sv99kXpI296FYAXX2ye79/UuBOmteYXNtkN0bDyjiO6qcU0BiEbNWWdB+mUvOkrFxaFkKg6deeM55/7+SNF1FhbLzOoZVXswfXpMTaZfw65GX2Pa2ikXCtkM90jaKb1psbAKvMSZWBpod2tMkeo8OihtTe3qBB2VaxllDcGAEOdkgThr/ZkNfPKc8gXqQKnw2hFcxSAzUiKGQXMbSWwLZwOzrU26nKT1HqdWKQOmKvNqzoHS3aIup8NgpCNvJHwCjHtxk='
spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl_auto: none
  h2:
    console:
      path: /h2-console               #h2 web控制台路径
      enabled: true                   #开启 Web Console
      settings:
        web-allow-others: true        #允许远程访问 Web Console
  datasource:
    platform: h2                      #指定数据源类型
    schema: classpath:schema.sql      #指定数据库的数据脚本
    data: classpath:data.sql          #指定数据库的数据脚本


logging:                           #配置日志级别，让Hibernate 打印执行的SQL
  level:
    org.springframework: info
    org.hibernate: info

management:
  security:
    enabled: false
  endpoints:
    web:
      base-path: /application
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: when_authorized
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:admin@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
#security:
#  basic:
#    enabled: true
#  user:
#    name: user
#    password: 123456